version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "nothing to do in the pre-build phase..."
  build:
    commands:
      - echo "build started..."
      - mvn clean install
  post_build:
    commands:
      - echo "updating lambda Function..."
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://./target/spring-cloud-function-aws-example-1.0-SNAPSHOT-aws.jar
      - echo "successfully updated lambda function"